### ISSUE TITLE
[请求数据库连接]页面，代码引用错误：

### ISSUE THREAD

**Issue by daimon99** [dormouse/Flask_Docs_ZhCn#17]
[请求数据库连接](http://dormousehole.readthedocs.org/en/latest/tutorial/dbcon.html)页面，代码引用错误：
原代码：
<pre><code>
@app.before_request
def before_request():
    g.db = connect_db()

@app.teardown_request
def teardown_request(exception):
    db = getattr(g, 'db', None)
    if db is not None:
        db.close()
    g.db.close()
</code></pre>
应该是：
<pre><code>
@app.before_request
def before_request():
    g.db = connect_db()

@app.teardown_request
def teardown_request(exception):
    db = getattr(g, 'db', None)
    if db is not None:
        db.close()
</code></pre>
<code>
    ~~g.db.close()~~
</code>

**Comment by dormouse** [comment]
已修正，非常感谢提醒！
