### ISSUE TITLE
困此 改为 因此

### ISSUE THREAD

**Issue by chenjiancong** [dormouse/Flask_Docs_ZhCn#20]
在[快速上手](http://dormousehole.readthedocs.org/en/latest/quickstart.html)里的**如何生成一个好的密钥中**“困此一个好的密钥应当有足够的随机性”
译者是打五笔的吧，这里打了个错别字是“因此”
感谢译者给我们的翻译！

**Comment by dormouse** [comment]
非常感谢提醒！
