### ISSUE TITLE
可以？可能？

### ISSUE THREAD

**Issue by RonaldZhao** [dormouse/Flask_Docs_ZhCn#21]
这样就启动了一个非常简单的内建的服务器。这个服务器用于测试应该是足够了。但是 用于生产可以是不够的。关于部署的有关内容参见《 部署方式 》。

上面这句中的“可以”应该为可能吧。

原文：
This launches a very simple builtin server, which is good enough for testing but probably not what you want to use in production. For deployment options see Deployment Options.

**Comment by dormouse** [comment]
您说得对，已修正。
非常感谢！
