### ISSUE TITLE
建议”context“翻译成”上下文“而非”情境“

### ISSUE THREAD

**Issue by Johnlisk** [dormouse/Flask_Docs_ZhCn#27]
典型例如如下两处：
https://dormousehole.readthedocs.io/en/latest/appcontext.html#id3
https://dormousehole.readthedocs.io/en/latest/reqcontext.html#id3
建立翻译成”请求上下文“和”应用上下文“，更加符合惯用翻译
（”惯用“可能需要讨论？我周围的开发者用”上下文“来描述flask的context更多）

**Comment by dormouse** [comment]
翻译成“上下文”的居多，但是我觉得“上下文”也不够准确，所以还是先保留为“情境”吧。

**Comment by Farmer-chong** [comment]
“上下文” 更加妥当

”情境“ 更加口语化

作为文档，个人偏向 ”上下文“ ，在无法找到更贴切的词代替且不满意现有翻译时 直接使用 context 或许更好的做法

**Comment by dormouse** [comment]
在找到更多的方案之前，暂时不动。
